name: Build All Platforms

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  trigger-builds:
    name: Trigger Platform Builds
    runs-on: ubuntu-latest
    steps:
      - name: Trigger macOS Build
        uses: actions/workflow_dispatch@v1
        with:
          workflow: macos.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Windows Build
        uses: actions/workflow_dispatch@v1
        with:
          workflow: windows.yml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Linux Build
        uses: actions/workflow_dispatch@v1
        with:
          workflow: linux.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger iOS Build
        uses: actions/workflow_dispatch@v1
        with:
          workflow: ios.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Android Build
        uses: actions/workflow_dispatch@v1
        with:
          workflow: android.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Web Build
        uses: actions/workflow_dispatch@v1
        with:
          workflow: web.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

  combine-artifacts:
    name: Combine All Artifacts
    runs-on: ubuntu-latest
    needs: trigger-builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all platform artifacts
        uses: actions/download-artifact@v4
        with:
            path: addons/godotcoacd/bin
            merge-multiple: true

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godotcoacd
          path: addons

      - name: Upload to Release (if release)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: addons
          token: ${{ secrets.GITHUB_TOKEN }}
