# -----------------------------------------------------------------------------
# This file was copied from the Godot C++ repository:
# https://github.com/godotengine/godot-cpp
#
# Original author(s): Godot Engine contributors
# License: MIT License
# Full license text included below:
# You can also view the original license here:
# https://github.com/godotengine/godot-cpp/blob/master/LICENSE.md
#
# MIT License
# Copyright (c) 2017-present Godot Engine contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# -----------------------------------------------------------------------------

name: Continuous integration
on:
  workflow_call:

env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  # Used to select the version of Godot to run the tests with.
  GODOT_TEST_VERSION: master
  # Use UTF-8 on Linux.
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

concurrency:
  group: ci-cmake-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-cmake:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      EM_VERSION: 4.0.11
      config-flags:
        -DCMAKE_C_COMPILER_LAUNCHER=sccache
        -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
        #REMOVED -DGODOTCPP_ENABLE_TESTING=ON
        #REMOVED -DGODOTCPP_BUILD_PROFILE="test/build_profile.json"
      SCCACHE_GHA_ENABLED: "true"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ðŸ§ Linux (GCC, Makefiles)
            os: ubuntu-22.04
            platform: linux
            config-flags: -DCMAKE_BUILD_TYPE=Release
            artifact-name: godot-cpp-linux-glibc2.27-x86_64-release.cmake
            artifact-path: cmake-build/bin/libgodot-cpp.linux.template_release.x86_64.a
            run-tests: false

          - name: ðŸ Windows (x86_64, MSVC)
            os: windows-2022
            platform: windows
            compiler: msvc
            build-flags: --config Release
            artifact-name: godot-cpp-windows-msvc2019-x86_64-release.cmake
            artifact-path: cmake-build/bin/libgodot-cpp.windows.template_release.x86_64.lib
            run-tests: false

          - name: ðŸŽ macOS (universal, Makefiles)
            os: macos-latest
            platform: macos
            config-flags: -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
            artifact-name: godot-cpp-macos-universal-release.cmake
            artifact-path: cmake-build/bin/libgodot-cpp.macos.template_release.universal.a
            run-tests: false

          - name: ðŸ¤– Android (arm64, Ninja)
            os: ubuntu-22.04
            platform: android
            config-flags:
              -G Ninja -DCMAKE_BUILD_TYPE=Release
              --toolchain ${ANDROID_HOME}/ndk/28.1.13356709/build/cmake/android.toolchain.cmake
              -DANDROID_PLATFORM=24 -DANDROID_ABI=arm64-v8a
            artifact-name: godot-cpp-android-arm64-release.cmake
            artifact-path: cmake-build/bin/libgodot-cpp.android.template_release.arm64.a
            flags: arch=arm64
            run-tests: false

          - name: ðŸ iOS (arm64, XCode)
            os: macos-latest
            platform: ios
            config-flags:
              -G Xcode
              --toolchain cmake/ios.toolchain.cmake
              -DPLATFORM=OS64
            build-flags: --config Release
            artifact-name: godot-cpp-ios-arm64-release.cmake
            artifact-path: cmake-build/bin/libgodot-cpp.ios.template_release.arm64.a
            flags: arch=arm64
            run-tests: false

          - name: ðŸŒ Web (wasm32, Ninja)
            os: ubuntu-22.04
            platform: web
            config-flags:
              -G Ninja  -DCMAKE_BUILD_TYPE=Release
              --toolchain ${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
            artifact-name: godot-cpp-web-wasm32-release.cmake
            artifact-path: cmake-build/bin/libgodot-cpp.web.template_release.wasm32.a
            run-tests: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Setup godot-cpp
        uses: ./.github/actions/setup-godot-cpp
        with:
          platform: ${{ matrix.platform }}
          windows-compiler: ${{ matrix.compiler }}
          buildtool: cmake

      - name: Configure godot-cpp-test with template_debug
        run: >
          cmake --log-level=VERBOSE -S . -B cmake-build ${{ env.config-flags }} ${{ matrix.config-flags }}

      - name: Build godot-cpp-test (template_debug)
        run: >
          cmake --build cmake-build --verbose  --target godotcoacd ${{ matrix.build-flags }} #REPLACED: godot-cpp-test -> godotcoacd

      - name: Configure godot-cpp-test with template_release
        run: >
          cmake --fresh --log-level=VERBOSE -S . -B cmake-build
          -DGODOTCPP_TARGET=template_release ${{ env.config-flags }} ${{ matrix.config-flags }}

      - name: Build godot-cpp-test (template_release)
        run: >
          cmake --build cmake-build --verbose  --target godotcoacd ${{ matrix.build-flags }} #REPLACED: godot-cpp-test -> godotcoacd

      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats

      - name: Download latest Godot artifacts
        uses: dsnopek/action-download-artifact@1322f74e2dac9feed2ee76a32d9ae1ca3b4cf4e9
        if: matrix.run-tests && env.GODOT_TEST_VERSION == 'master'
        with:
          repo: godotengine/godot
          branch: master
          event: push
          workflow: linux_builds.yml
          workflow_conclusion: success
          name: linux-editor-mono
          search_artifacts: true
          check_artifacts: true
          ensure_latest: true
          path: godot-artifacts

      - name: Prepare Godot artifacts for testing
        if: matrix.run-tests && env.GODOT_TEST_VERSION == 'master'
        run: |
          chmod +x ./godot-artifacts/godot.linuxbsd.editor.x86_64.mono
          echo "GODOT=$(pwd)/godot-artifacts/godot.linuxbsd.editor.x86_64.mono" >> $GITHUB_ENV

      - name: Download requested Godot version for testing
        if: matrix.run-tests && env.GODOT_TEST_VERSION != 'master'
        run: |
          wget "https://github.com/godotengine/godot-builds/releases/download/${GODOT_TEST_VERSION}/Godot_v${GODOT_TEST_VERSION}_linux.x86_64.zip" -O Godot.zip
          unzip -a Godot.zip
          chmod +x "Godot_v${GODOT_TEST_VERSION}_linux.x86_64"
          echo "GODOT=$(pwd)/Godot_v${GODOT_TEST_VERSION}_linux.x86_64" >> $GITHUB_ENV

      - name: Run tests
        if: matrix.run-tests
        run: |
          $GODOT --headless --version
          cd test
          # Need to run the editor so .godot is generated... but it crashes! Ignore that :-)
          (cd project && (timeout 30 $GODOT --import --headless >/dev/null 2>&1 || true))
          ./run-tests.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
          if-no-files-found: error
