name: Build godotcoacd for Web

on:
  workflow_call:
  workflow_dispatch:

jobs:
  emscripten:
    runs-on: ubuntu-latest
    name: wasm32 - ${{ matrix.target }} - threads=${{ matrix.threads }}

    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        threads: [ON, OFF]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Configure CMake
        run: >
          emcmake cmake -S . -B build
          -G "Unix Makefiles"
          -DCMAKE_BUILD_TYPE=Release
          -DGODOTCPP_TARGET=${{ matrix.target }}
          -DGODOTCPP_THREADS=${{ matrix.threads }}

      - name: Build godotcoacd
        run: cmake --build build --target godotcoacd --parallel $(nproc)

      - name: Prepare artifact
        shell: bash
        run: |
          if [ "${{ matrix.threads }}" == "OFF" ]; then
            ARTIFACT_DIR="artifact/web.wasm32.nothreads"
          else
            ARTIFACT_DIR="artifact/web.wasm32"
          fi
          mkdir -p "$ARTIFACT_DIR"
          cp -r build/godotcoacd_release/* "$ARTIFACT_DIR/"


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godotcoacd-web-wasm32-${{ matrix.target }}-threads=${{ matrix.threads }}
          path: artifact/